### PR TITLE
Fix module not found for RouterContext

### LINKED ISSUE #80: Module not found: Can't resolve 'next/dist/shared/lib/router-context'
On the latest version of Next.js (13.5.1), compilation fails due to a Next module which is not found within the next-translate-routes package.

This is the message which is shown in my console:
`
../../node_modules/next-translate-routes/react/withTranslateRoutes.js:38:0
Module not found: Can't resolve 'next/dist/shared/lib/router-context'
`

### PR DESCRIPTION
**Pull request by cvolant**
Rework [PR#81](https://github.com/hozana/next-translate-routes/pull/81) to tackle it using Webpack instead of try-catch dynamic imports.

Fix #80

### CODE REVIEW

**Comment by cvolant** [comment]
@sdk1990

**Comment by ristomatti** [comment]
@cvolant Any plans when this will be published? We just bumped into this.

**Comment by erikgreasy** [comment]
@cvolant any updates on this?

**Comment by cvolant** [comment]
Yes, sorry that it took so long. I published it in a prerelease: next-translate-routes@1.11.0-0.
I will probably publish 1.11.0 next week.

**Comment by cvolant** [comment]
Yes, it is. :face_exhaling:
I first tried to use Webpack alias for v11.0.0: it worked on my machine but not everywhere, I don't know why.
Then I tried some other solutions without more success for now: the error you get happens because I tried with Webpack DefinePlugin...

**Pull request merged**
