### PR TITLE
Fix catch-all conflicts

### PR DESCRIPTION
**Pull request by cvolant**
This PR fixes the same issue than [this other PR](https://github.com/hozana/next-translate-routes/pull/78).

- Change a regex to fix the issue
- Add a new test

### CODE REVIEW

**Comment by cvolant** [comment]
@gercordero

**Comment by gercordero** [comment]
> @gercordero

You almost got it working. I have tested your changes for all the example routes on the codepen I shared on my other pr and the only route that is not being translated properly is `/men/shoes/sneakers` which should be translated to `/hombres/shoes/sneakers` 😄

**Comment by cvolant** [comment]
Strange... I downloaded your sandbox and plugged it on my branch and it works, even for the `/hombres/shoes/sneakers`...
How did you test the changes @gercordero?

**Comment by gercordero** [comment]
> Strange... I downloaded your sandbox and plugged it on my branch and it works, even for the `/hombres/shoes/sneakers`... How did you test the changes @gercordero?

I have done exactly the same as you to try to test your changes. I've tried it both in my local machine and in codesandox and the behaviour is the same as I reported before regarding the `/men/shoes/sneakers` route. Please have a look yourself here:

https://codesandbox.io/p/sandbox/fix-catch-all-conflicts-83-7rzttd

**Comment by cvolant** [comment]
In the codesandbox you linked to, the installed next-translate-routes package is the previous one, without the changes...
I am going to merge this PR, and publish it in a 1.11.0-1 prerelease, and we will see.

**Comment by cvolant** [comment]
If you tried with 1.11.0-1 and it did not work, please try with 1.11.0-5: I finally had some time to look into the issue and deployed a fix. I had to drop support for next < 13.5.0 though.

**Pull request merged**
